version: '3.8'
services:
  db:
    image: postgres:15
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    command: gunicorn gutenberg_api.wsgi:application --bind 0.0.0.0:8000
    env_file: .env
    ports:
      - '8000:8000'
    depends_on:
      - db
volumes:
  postgres_data: